#  Karşılaştırma Operatörleri

In [1]:
2==1

False

In [2]:
2==(1+1)

True

In [3]:
"intermediate"!="python"

True

In [4]:
True!=False

True

In [5]:
"Python"!="python"

True

In [6]:
3<4

True

In [9]:
3<=4 # Küçük eşit yada büyük eşit yada eşit değil hepsinde = işareti sağ tarafta yer alır

True

In [8]:
"alpha"<"beta" # python string karşılaştırmalarında alfabetik sıralamayı kullanır. Bu sebeple true dönüş yapar.

True

In [10]:
True>False # True sayısal değeri 1 False sayısal değeri 0 olduğu için bu karşılaştırma True değeri döner.

True

In [11]:
# numpy arrayler üzerinde karşılaştırma yapılabilir. Bunun için iki tane array yaratıyorum.
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [12]:
my_house<18 # my_house içerisindeki 18'den küçük değerleri buluruz.

array([False, False,  True,  True])

In [14]:
my_house<your_house # İki array içindeki aynı indeksli değerleri karşılaştırır. my_house üzerindei değer küçük ise True değerini döner.

array([False,  True,  True, False])

# Boolean Operatörleri

Numpy dizileri arasında karşılaştırma operatörleri kullanmak için direkt AND, OR, NOT kullanılmaz. Buna ihtiyaç duyduğumuzda logical_and(), logical_or() ve logical_not() kullanırız. "numpy.logical_and(array_a>21, array_a<18)"

Eğer array içerisinde True gelen değerleri bulmak istersek array_a[numpy.logical_and(array_a>21, array_a<18)] ile True gelen değerleri içeren bir array elde ederiz.

In [16]:
# İki tane değişken yaratıyorum
mutfak=18
banyo=14

In [17]:
banyo>10 and banyo<18 # Her ikisi de True iken True olur.

True

In [18]:
mutfak>10 and mutfak<18

False

In [19]:
mutfak>10 or mutfak<18 # Yanlızca biri bile True olsa True döner.

True

In [20]:
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

In [21]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [23]:
np.logical_and(my_house<10,your_house<10) # İki array içerisinde aynı indeksteki değerlerden her ikisi de 10'dan küçük ise True

array([False, False, False,  True])

In [26]:
np.logical_or(my_house>18,my_house<10) # my_house içerisinde 18'den büyük ve 10'dan küçük değerler içi True

array([False,  True, False,  True])