# Python içerisinden dışarıdaki verilerin okunması

Üç temel kaynaktan veri okunabilir. 

* Text dosyalar. Örnek olarak .txt, .csv ve benzeri
* Başka uygulamarın ürettiği dosyalar. Örnek olarak excel dosyaları
* İlişkisel veritabanı sistemleri. MSSQL, MYSQL, Oracle ve benzeri


## Text dosyaların içerisinden data alınması

Python içerisinde **open(*filename*,mode='r/w')** ile yaratılacak bir dosya objesi üzerinden bir dosya içindeki veriler yazılıp okunabilir.

In [3]:
file=open('D:\ML_DATA\Prophecies of _Daniel_Newton.txt', mode='r') # r read-only anlamındadır.

In [4]:
text=file.read() # Tanımlanan dosyayı okuyup text değişkenin içine yüklüyoruz.

In [5]:
print(text)

The Project Gutenberg EBook of Observations upon the Prophecies of Daniel,
and the Apocalypse of St. John, by Isaac Newton

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: Observations upon the Prophecies of Daniel, and the Apocalypse of St. John

Author: Isaac Newton

Release Date: October 15, 2005 [EBook #16878]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK OBSERVATIONS UPON THE ***




Produced by Greg Alethoup, Robert Shimmin, Keith Edkins
and the Online Distributed Proofreading Team at
http://www.pgdp.net





OBSERVATIONS
UPON THE
PROPHECIES
OF
_DANIEL_,
AND THE
APOCALYPSE
OF
St. _JOHN_.

       *       *       *       *       *

In Two PARTS.

       *       *       *       *       *

By Sir _ISAAC NEWTON_.

       *       *       *       *       *

_LO

In [6]:
file.close() # Memory üzerinden silmek için close ile file objesini kapatıyoruz.

Ayrı olarak open ve close ile uğraşmak istemiyorsak **Context Manager** ile *with open(filename, mode='r/w') as file* şekilnde tanımlanacak file objesi sayessinde çağırıldığında okunur ve işi bitince otomatik olarak kapanır 

In [7]:
with open('D:\ML_DATA\Prophecies of _Daniel_Newton.txt', mode='r') as file:
    print(file.read())

The Project Gutenberg EBook of Observations upon the Prophecies of Daniel,
and the Apocalypse of St. John, by Isaac Newton

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: Observations upon the Prophecies of Daniel, and the Apocalypse of St. John

Author: Isaac Newton

Release Date: October 15, 2005 [EBook #16878]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK OBSERVATIONS UPON THE ***




Produced by Greg Alethoup, Robert Shimmin, Keith Edkins
and the Online Distributed Proofreading Team at
http://www.pgdp.net





OBSERVATIONS
UPON THE
PROPHECIES
OF
_DANIEL_,
AND THE
APOCALYPSE
OF
St. _JOHN_.

       *       *       *       *       *

In Two PARTS.

       *       *       *       *       *

By Sir _ISAAC NEWTON_.

       *       *       *       *       *

_LO

## Numpy ile text dosyların içerisinden veri alınması

Bunun için **loadtxt()** yada **genfromtxt()** kullanılabilir. Delimiter olarak tab kullanmak istersek **"\t"** kullanırız.

In [8]:
import numpy as np

In [10]:
filename='D:\ML_DATA\mnist_train.csv'

data=np.loadtxt(filename,delimiter=',') # Bu komut ile dosyayı numpy array içine yüklüyoruz.

In [11]:
data

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.]])

**<span style="color:red">
Eğer dosya içerisinde ilk satırda başlıklar var ise</span>**

In [13]:
filename='D:\ML_DATA\mnist_train_header.csv'
data=np.loadtxt(filename,delimiter=',',skiprows=1) # skiprows ile kaç tane satırı almaması gerektiğini beirtiyoruz.

In [14]:
data

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       [8., 0., 0., ..., 0., 0., 0.]])

Sadece **belirli kolonları** almak istiyorsak **usecols** parametresini kullanabiliriz. Burada almak istediğimiz kolonların index numaralarını tek tek yazarız.

In [28]:
filename='D:\ML_DATA\mnist_train_header.csv'
data=np.loadtxt(filename,delimiter=',',skiprows=1, usecols=[0,5,8])

In [29]:
data

array([[5., 0., 0.],
       [0., 0., 0.],
       [4., 0., 0.],
       ...,
       [5., 0., 0.],
       [6., 0., 0.],
       [8., 0., 0.]])

In [25]:
filename='D:\ML_DATA\mnist_train_header.csv'
data=np.loadtxt(filename,delimiter=',',dtype=str) # ilk satır string olduğu için onunla birlikte tüm veriliri strin olarak aldık.

In [24]:
data

array([['label', '1x1', '1x2', ..., '28x26', '28x27', '28x28'],
       ['5', '0', '0', ..., '0', '0', '0'],
       ['0', '0', '0', ..., '0', '0', '0'],
       ...,
       ['5', '0', '0', ..., '0', '0', '0'],
       ['6', '0', '0', ..., '0', '0', '0'],
       ['8', '0', '0', ..., '0', '0', '0']], dtype='<U5')

**<span style="color:blue">Birden farklı data tipinde veri yüklemek</span>**

Eğer ki dosya içinde değişik veri tipleri bulunuyor ise, bunun için **genfromtxt()** kullanılabilir. Bir diğer yöntem **recfromcsv()**

In [38]:
filename='titanic.csv'
data=np.genfromtxt('titanic.csv',delimiter=',',names=True,dtype=None,encoding=None) # Bu şekilde yüklenen structured data

In [36]:
data

array([(  1, 0, 3, 'male', 22.  , 1, 0, 'A/5 21171',   7.25  , '', 'S'),
       (  2, 1, 1, 'female', 38.  , 1, 0, 'PC 17599',  71.2833, 'C85', 'C'),
       (  3, 1, 3, 'female', 26.  , 0, 0, 'STON/O2. 3101282',   7.925 , '', 'S'),
       (  4, 1, 1, 'female', 35.  , 1, 0, '113803',  53.1   , 'C123', 'S'),
       (  5, 0, 3, 'male', 35.  , 0, 0, '373450',   8.05  , '', 'S'),
       (  6, 0, 3, 'male',   nan, 0, 0, '330877',   8.4583, '', 'Q'),
       (  7, 0, 1, 'male', 54.  , 0, 0, '17463',  51.8625, 'E46', 'S'),
       (  8, 0, 3, 'male',  2.  , 3, 1, '349909',  21.075 , '', 'S'),
       (  9, 1, 3, 'female', 27.  , 0, 2, '347742',  11.1333, '', 'S'),
       ( 10, 1, 2, 'female', 14.  , 1, 0, '237736',  30.0708, '', 'C'),
       ( 11, 1, 3, 'female',  4.  , 1, 1, 'PP 9549',  16.7   , 'G6', 'S'),
       ( 12, 1, 1, 'female', 58.  , 0, 0, '113783',  26.55  , 'C103', 'S'),
       ( 13, 0, 3, 'male', 20.  , 0, 0, 'A/5. 2151',   8.05  , '', 'S'),
       ( 14, 0, 3, 'male', 39.  , 1, 5, '3

In [37]:
data['Fare']

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0