# Linear Regression & Multiple Linear Regression

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
path='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/automobileEDA.csv'

In [3]:
df=pd.read_csv(path)

In [4]:
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

Öncelikle hangi alanlar arasında korelasyon olduğunu anlamaya çalışacağız. Aşağıdaki tablodan price ile en yüksek korelasyonun engine-size arasında olduğunu görüyoruz.

In [8]:
df.corr()

symboling  normalized-losses  wheel-base    length  \
symboling           1.000000           0.466264   -0.535987 -0.365404   
normalized-losses   0.466264           1.000000   -0.056661  0.019424   
wheel-base         -0.535987          -0.056661    1.000000  0.876024   
length             -0.365404           0.019424    0.876024  1.000000   
width              -0.242423           0.086802    0.814507  0.857170   
height             -0.550160          -0.373737    0.590742  0.492063   
curb-weight        -0.233118           0.099404    0.782097  0.880665   
engine-size        -0.110581           0.112360    0.572027  0.685025   
bore               -0.140019          -0.029862    0.493244  0.608971   
stroke             -0.008245           0.055563    0.158502  0.124139   
compression-ratio  -0.182196          -0.114713    0.250313  0.159733   
horsepower          0.075819           0.217299    0.371147  0.579821   
peak-rpm            0.279740           0.239543   -0.360305 -0.285970   
city-mpg           -0.035527          -0.225016   -0.470606 -0.665192   
highway-mpg         0.036233          -0.181877   -0.543304 -0.698142   
price              -0.082391           0.133999    0.584642  0.690628   
city-L/100km        0.066171           0.238567    0.476153  0.657373   
diesel             -0.196735          -0.101546    0.307237  0.211187   
gas                 0.196735           0.101546   -0.307237 -0.211187   

                      width    height  curb-weight  engine-size      bore  \
symboling         -0.242423 -0.550160    -0.233118    -0.110581 -0.140019   
normalized-losses  0.086802 -0.373737     0.099404     0.112360 -0.029862   
wheel-base         0.814507  0.590742     0.782097     0.572027  0.493244   
length             0.857170  0.492063     0.880665     0.685025  0.608971   
width              1.000000  0.306002     0.866201     0.729436  0.544885   
height             0.306002  1.000000     0.307581     0.074694  0.180449   
curb-weight        0.866201  0.307581     1.000000     0.849072  0.644060   
engine-size        0.729436  0.074694     0.849072     1.000000  0.572609   
bore               0.544885  0.180449     0.644060     0.572609  1.000000   
stroke             0.188829 -0.062704     0.167562     0.209523 -0.055390   
compression-ratio  0.189867  0.259737     0.156433     0.028889  0.001263   
horsepower         0.615077 -0.087027     0.757976     0.822676  0.566936   
peak-rpm          -0.245800 -0.309974    -0.279361    -0.256733 -0.267392   
city-mpg          -0.633531 -0.049800    -0.749543    -0.650546 -0.582027   
highway-mpg       -0.680635 -0.104812    -0.794889    -0.679571 -0.591309   
price              0.751265  0.135486     0.834415     0.872335  0.543155   
city-L/100km       0.673363  0.003811     0.785353     0.745059  0.554610   
diesel             0.244356  0.281578     0.221046     0.070779  0.054458   
gas               -0.244356 -0.281578    -0.221046    -0.070779 -0.054458   

                     stroke  compression-ratio  horsepower  peak-rpm  \
symboling         -0.008245          -0.182196    0.075819  0.279740   
normalized-losses  0.055563          -0.114713    0.217299  0.239543   
wheel-base         0.158502           0.250313    0.371147 -0.360305   
length             0.124139           0.159733    0.579821 -0.285970   
width              0.188829           0.189867    0.615077 -0.245800   
height            -0.062704           0.259737   -0.087027 -0.309974   
curb-weight        0.167562           0.156433    0.757976 -0.279361   
engine-size        0.209523           0.028889    0.822676 -0.256733   
bore              -0.055390           0.001263    0.566936 -0.267392   
stroke             1.000000           0.187923    0.098462 -0.065713   
compression-ratio  0.187923           1.000000   -0.214514 -0.435780   
horsepower         0.098462          -0.214514    1.000000  0.107885   
peak-rpm          -0.065713          -0.435780    0.107885  1.000000   
city-mpg 

***Tek boyutlu linear regression***

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lm=LinearRegression()

In [12]:
X=df[["engine-size"]] # Bunu df olarak alacağım.

In [16]:
Y=df["price"] # Bunu ise bir seri olarak alıyorum

In [17]:
X

engine-size
0            130
1            130
2            152
3            109
4            136
..           ...
196          141
197          141
198          173
199          145
200          141

[201 rows x 1 columns]

In [18]:
Y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...   
196    16845.0
197    19045.0
198    21485.0
199    22470.0
200    22625.0
Name: price, Length: 201, dtype: float64

In [19]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
sabit=lm.intercept_

In [21]:
egim=lm.coef_

In [22]:
sabit

-7963.338906281024

In [24]:
egim

array([166.86001569])

In [37]:
lm.predict(X)

array([13728.4631336 , 13728.4631336 , 17399.38347881, 10224.40280408,
       14729.62322775, 14729.62322775, 14729.62322775, 14729.62322775,
       13895.32314929, 10057.54278839, 10057.54278839, 19401.70366711,
       19401.70366711, 19401.70366711, 26910.40437322, 26910.40437322,
       26910.40437322,  2215.1220509 ,  7054.06250595,  7054.06250595,
        7054.06250595,  7054.06250595,  8388.94263148,  7054.06250595,
        7054.06250595,  7054.06250595,  8388.94263148, 12393.58300807,
       18066.82354158,  7387.78253733,  7387.78253733,  5218.60233334,
        7387.78253733,  7387.78253733,  7387.78253733,  7387.78253733,
       10391.26281977, 10391.26281977, 10391.26281977, 10391.26281977,
       10391.26281977, 10391.26281977, 10558.12283547, 11893.002961  ,
       35086.5451421 , 35086.5451421 , 46433.02620912,  7220.92252164,
        7220.92252164,  7220.92252164,  7220.92252164,  7220.92252164,
        3716.86219212,  3716.86219212,  3716.86219212,  5385.46234903,
      

In [42]:
#bulduğumuz değerler ile prediction
x=130
y=sabit+egim*x
y[0]

13728.463133603032

In [46]:
df[df["engine-size"]==130][["engine-size","price"]]
#Gerçek değer

engine-size    price
0            130  13495.0
1            130  16500.0
194          130  18420.0
195          130  18950.0

Görüldüğü gibi korelasyon yüksek olsa bile tam doğru sonuç diye bir şey yok. Olası en yakın sonucu tahmin etmeye çalışıyoruz. Şimdi parametre sayısını arttırarak regresyon yapalım.  curb-weight horsepower width değerlerini de alalım

In [49]:
X=df[["engine-size","curb-weight","horsepower","width"]] 

In [50]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
sabit=lm.intercept_
egim=lm.coef_

In [52]:
sabit

-49492.75867088131

In [53]:
egim

array([8.20797406e+01, 2.07560675e+00, 5.35640647e+01, 4.52862240e+04])

In [54]:
df[df["engine-size"]==130][["engine-size","price","curb-weight","horsepower","width"]]
#Gerçek değer

engine-size    price  curb-weight  horsepower     width
0            130  13495.0         2548       111.0  0.890278
1            130  16500.0         2548       111.0  0.890278
194          130  18420.0         3045       162.0  0.933333
195          130  18950.0         3157       162.0  0.933333

In [58]:
#bulduğumuz değerler ile prediction
x=130
z=2548
t=111
p=0.890278
y=sabit+egim[0]*x+egim[1]*z+egim[2]*t+egim[3]*p
y

12729.193755679556